version: "3.9"

services:
  api:
    image: ${DOCKERHUB_USER}/music-api:latest
    container_name: music-api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: always

  bot:
    image: ${DOCKERHUB_USER}/music-bot:latest
    container_name: music-bot
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./logs:/app/logs
    restart: always