version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: music-api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: always

  bot:
    build:
      context: .
      dockerfile: tg_bot/Dockerfile
    container_name: music-bot
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./logs:/app/logs
    restart: always